### ISSUE TITLE
Warning message after Task 2 and Task 4 in executeStudy.R

### ISSUE THREAD

**Issue by siirsu** [OdyOSG/ehden_hmb#10]
**Describe the bug**
This is not exactly a bug, however some warning messages pops up which might be relevant.

**To Reproduce**
1. Go to 'executeStudy.R'
2. Run line 30 'Task 2: Run Cohort Diagnostics' and line 36 'Task 4: Run Baseline Characteristics'
3. Wait until the tasks run to completion
4. See the warning message

**Screenshots**
After Task 2 
<img width="360" alt="HMB-Task 2 - warning message " src="https://github.com/OdyOSG/ehden_hmb/assets/96056830/e044ddfc-3cde-49f8-8ec2-42f7e3633e66">

After Task 4
<img width="351" alt="HMB-Task 4 - warning message" src="https://github.com/OdyOSG/ehden_hmb/assets/96056830/52608c36-859c-48d1-8052-bb58b89c8cf4">

**Additional context**
Not sure if this relates to an unused argument in the code or whether there is anything missing for the output.

**Comment by mdlavallee92** [comment]
the warning after task 2 is expected...just ignore it. I think it is something come from deep within CohortDiagnostics. it is an unused argument

the warning after task 4 I have corrected the bug to be pushed in the next release
