### ISSUE TITLE
Output of treatment patterns does not match with treatment cohort categories 

### ISSUE THREAD

**Issue by siirsu** [OdyOSG/ehden_hmb#12]
**Describe the bug**
Treatment patterns analysis do not contain the right treatment groups based on the updated json files of treatment cohorts.

**To Reproduce**
1. Go to 'postIndexPrevalence1.yml' and 'treatmentPatterns1.yml' and 'treatmentPatterns2.yml' files which are used for Task 5 in 'executeStudy.R' 
2. Scroll down to 'drugCohorts'
4. See the drug cohorts do not correspond to the json files in 04_drugExposure under cohortsToCreate folder of the study package

**Expected behavior**
Currently the results are produced for combOralContraceptives, danazol, grha, ironPreparations, iud, nsaids, progestin, progresteron and tranexamicAcid while progestin needs to be changed to progestinOnly and progesteron needs to be replaced with ulipristalAcetate. Additionally, not sure if the cohortIds generated at the end of Task 1 should match with ids described in the yaml files, since this is not currently the case.

**Comment by mdlavallee92** [comment]
Ok weird, I thought I reset the settings files when I added the new cohorts. Let me refresh the yml files and then you can rerun

**Comment by mdlavallee92** [comment]
fixed in v0.1.5
