### ISSUE TITLE
Issue when running Task2 cohortDiagnostics 

### ISSUE THREAD

**Issue by palilsonjmr** [OdyOSG/ehden_hmb#22]
**Describe the bug**
Hi, 

I got this error when executing the package when I was executing the following command in the executeStudy.R file:

> # Task 2: Run Cohort Diagnostics
> runStudyTask(file = studyTaskFiles[2], configBlock = configBlock)

Error in length(packageName) != 0 && !packageName %in% c("base", "snow",  : 
  'length = 2' in coercion to 'logical(1)'
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error in deparse(x[[1L]]) : 
  (converted from warning) NAs introduced by coercion
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error in deparse(x[[1L]]) : 
  (converted from warning) NAs introduced by coercion
Error in paste(sigs[short], suffix, sep = "#") : 
  (converted from warning) NAs introduced by coercion

Please find attached the log.txt file found in the 02_cohortDiagnostics folder.
 
[log.txt](https://github.com/OdyOSG/ehden_hmb/files/13024950/log.txt)

**To Reproduce**

runStudyTask(file = studyTaskFiles[2], configBlock = configBlock)

**Expected behavior**

**Screenshots**

**Environment**
 - Operating System
    Operating System: Ubuntu 20.04.5 LTS
    Kernel: Linux 5.14.0-1057-oem
    Architecture: x86-64

 - Version of R
    4.3.1
 - If `renv` not used provide snapshot of active packages
    renv was used.

**Additional context**

Best Regards,
Juanma

**Comment by mdlavallee92** [comment]
Hi @palilsonjmr thanks for submitting your issue. I need a bit more context in order to help resolve this....were you able to successfully build cohorts in [step 1](https://github.com/OdyOSG/ehden_hmb/blob/main/executeStudy.R#L27C1-L27C66)? Can you run any of the remaining tasks after cohort diagnostics?

**Comment by mdlavallee92** [comment]
Another question...what dbms are you using?

**Comment by palilsonjmr** [comment]
Hi @mdlavallee92 ,

I am using postgresql as a dbms and the step1 was executed correctly or at least I did not see any error message. The folder 01_buildCohorts was created and it contains the files cohortManifest.csv and  GeneratedCohorts.csv. If you miss some other files here let me know.

In addition, the 02_cohortDiagnostics folder was created too and it contains the following files:
cohort_count.csv  cohort_inclusion.csv   cohort_inc_stats.csv      concept_sets.csv  executionTimes.csv   log.txt   cohort.csv     cohort_inc_result.csv  cohort_summary_stats.csv  database.csv      included_source_concept.csv  index_event_breakdown.csv.

Within this folder the subfolder "incremental" was also created and It contains just one file: CreatedDiagnostics.csv
If you want me to share these files, let me now.

**Comment by mdlavallee92** [comment]
for now continue with the other steps (3-6) and see if you are getting additional errors. Come back to the diagnostics later...

I will take a closer look at this to see why you are getting this error but need a bit of time. It seems like the issues are coming from your vocabulary (ie your data) and not something with the code itself (at first glance). Do you have a separate vocab schema to your cdm schema?

**Comment by palilsonjmr** [comment]
The vocab schema is the same one than the cdm schema. Maybe there is a vocabulary that you use and it is missing in my vocabularies? For example I have ICD10CM and ICD9CM but I do not have ICD10. I saw some outputs when running the remaining tasks in which the message "Building ICD 10 Rollup". If this means the ICD10 vocabulary is needed, this would be a problem. 

I have run the next steps and I got another error. I will open a new issue for these one

**Comment by mdlavallee92** [comment]
Sorry for the delay @palilsonjmr I was at the OHDSI symposium so wasnt able to focus on these errors. No that ICD rollup should be fine.

Can you send me the output you have so far for cohort diagnostics via email? 

I still think this is probably a data issue given what I am seeing in the logs but want to make sure.
