### ISSUE TITLE
issue when running task4

### ISSUE THREAD

**Issue by palilsonjmr** [OdyOSG/ehden_hmb#23]
**Describe the bug**

Hi,

I got this error when executing the package when I was executing the following command in the executeStudy.R file:

> # Task 4: Run Baseline Characteristics
> runStudyTask(file = studyTaskFiles[4], configBlock = configBlock)

_── Build Cohort Covariates ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 _Error in check_unsupported_arg(.preserve, FALSE) : 
could not find function "check_unsupported_arg"
14. filter.tbl_lazy(., cohort_definition_id %in% targetId)
13. dplyr::filter(., cohort_definition_id %in% targetId)
12. dplyr::count(., cohort_definition_id)
11. dplyr::collect(.)
10. dplyr::right_join(., cohortKey, by = c(cohort_definition_id = "id"))
9. dplyr::rename(., id = cohort_definition_id)
8. dplyr::select(., id, name, n)
7. dplyr::arrange(., id)
6. dplyr::tbl(con, dbplyr::in_schema(cohortDatabaseSchema, cohortTable)) %>% 
dplyr::filter(cohort_definition_id %in% targetId) %>% dplyr::count(cohort_definition_id) %>% 
dplyr::collect() %>% dplyr::right_join(cohortKey, by = c(cohort_definition_id = "id")) %>% 
dplyr::rename(id = cohort_definition_id) %>% dplyr::select(id, ... at _cohortPrevalence.R#65
5. cohortCovariates(con = con, cohortDatabaseSchema = workDatabaseSchema, 
cohortTable = cohortTable, cohortKey = cohortKey, covariateKey = covariateKey, 
timeA = timeA[i], timeB = timeB[i], outputFolder = outputFolder) at _cohortPrevalence.R#158
4.executeCohortPrevalence(con = con, executionSettings = executionSettings, 
analysisSettings = analysisSettings2)
3.eval(exprs[[i]], env)
2.eval(exprs[[i]], env) at _executeStudy.R#45
1.runStudyTask(file = studyTaskFiles[4], configBlock = configBlock)__

**Environment**
Operating System: Ubuntu 20.04.5 LTS
Kernel: Linux 5.14.0-1057-oem
Architecture: x86-64

Version of R
4.3.1

If renv not used provide snapshot of active packages
renv was used.

dbms: postgresql

**Additional context**

The folder 04_incidenceAnalysis was created and it contains this files:
incidence_analysis_ref_1.csv  incidence_analysis_ref_2.csv  incidence_analysis_ref_3.csv  incidence_analysis_ref_4.csv
They seem to be ok but I am not sure if any other file should be in this folder.

In addition the 05_baselineCharacteristics is also created and contains the files:
cohort_covariates_365_0.csv  conditions_baseline.csv  demographics_baseline.csv  procedures_baseline.csv
condition_chapters.csv       continuous_baseline.csv  drugs_baseline.csv

This is unexpected as the error arose when executing task4... 
I did not find any other log file to share with you. If you need some of the results files or extra feedback, let me know.

**Comment by mdlavallee92** [comment]
correct this does not have a log file....will need to be a future addition for this process. 

send me all your output via email please so I can review.

Looking at this issue I am wondering if the cohort build ran properly.

**Comment by ZorzArg** [comment]
Hi @palilsonjmr,

Please try to install and run this version of the [package ](https://github.com/OdyOSG/ehden_hmb/tree/delMar).

The package code has been amended in order to run Task 4 successfully as well as Cohort Diagnostics (the issue posted [here](https://github.com/OdyOSG/ehden_hmb/issues/22)).

Give it a try and let us know if there are any issues.
