### ISSUE TITLE
Issue SQL error in _buildStrata for SQL Server and Synapse dialects

### ISSUE THREAD

**Issue by eric-fey-hus** [OdyOSG/ehden_hmb#27]
**Describe the bug**
SQL error in _buildStrata for SQL Server and Synapse dialects.

**To Reproduce**
1. Set connection details for Azure Synapse,  that is `dbms = "synapse"`
2. Run 01_buildCohorts.R, and more specifically `buildStrata(...)` in line 74
4. See error:

> DBMS:
> synapse
> 
> Error:
> com.microsoft.sqlserver.jdbc.SQLServerException: Parse error at line: 23, column: 49: Incorrect syntax near 'FROM'.
> 

**Expected behavior**
Code should run error-free on any database system and sql dialect, including Synapse.

I could solve this by modifying the sql query code in `_buildStrata` line 78
```sql
-    abs(p.year_of_birth - EXTRACT(YEAR FROM c.cohort_start_date)) AS age
+    abs(p.year_of_birth - YEAR(c.cohort_start_date)) AS age
```
SQL Server and Synapse use function YEAR(...), not EXTRACT( YEAR FROM ...).

**Environment**
 - Windows
 - Version of R = 4.2.1
 - `renv` used 
 -  dbms = synapse

**Comment by ZorzArg** [comment]
Hi @eric-fey-hus,

We'll make the necessary changes and add them in the next package release.
