### ISSUE TITLE
Connection parameter in redshift

### ISSUE THREAD

**Issue by rfherrerac** [OdyOSG/ehden_hmb#9]
Hi, when trying first task (build cohorts) I am getting: 

Connecting using Redshift driver
Error in `connectUsingJdbcDriver()`:
! Unable to connect JDBC to 10.8.19.50/cegedim_thinbe_omop
when changing in the function
**connectionDetails** the parameter **connectionString** to **server** it works.

**Comment by mdlavallee92** [comment]
it could be the connection string is incorrect? A bit hard to fix this as I need a reproducible example but dont want you to send any credentials. We can try to debug this offline if it is still causing a problem

**Comment by rfherrerac** [comment]
I just changed the parameter connectionString to server and it worked.
